[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_DISABLE_ESLINT = "1"
  NEXT_DISABLE_TYPECHECK = "1"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), fullscreen=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"


