[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_DISABLE_ESLINT = "1"
  NEXT_DISABLE_TYPECHECK = "1"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"


